### ISSUE TITLE
service discovery (consul): removal of a service in the consul (used backend) stops further updates of haproxy configs

### ISSUE THREAD

**Issue by focuzz** [haproxytech/dataplaneapi#200]
When stoping task in nomad, nomad removes service in consul, and this renders dataplaneapi unconscious if that backend is in use by a frontend, even when service is recreated in the future.

Proposed solution: if used backed is removed, dependant frontend should be disabled (by commenting).

Configuration:
```
OS: Debian 11 (Linux 5.10.0-7-amd64 #1 SMP Debian 5.10.40-1 (2021-05-28) x86_64)
HAproxy: HAProxy version 2.4.2-1~bpo11+1 2021/07/07
HAProxy Data Plane API: v2.3.2 5344362
Consul: 1.10.1
```

/etc/haproxy/dataplaneapi.yaml
```
config_version: 2
name: haproxy1
mode: single
status: ""
dataplaneapi:
  host: 172.27.2.170
  port: 5555
  user:
  - name: dataplaneapi
    insecure: true
    password: mypassword
  advertised:
    api_address: ""
    api_port: 0
haproxy:
  config_file: /etc/haproxy/haproxy.cfg
  haproxy_bin: /usr/sbin/haproxy
  reload:
    reload_delay: 5
    reload_cmd: service haproxy reload
    restart_cmd: service haproxy restart
service_discovery:
  consuls:
  - address: 127.0.0.1
    description: ""
    enabled: true
    id: 8d4e2d4f-1ad9-4619-bd9c-80e200323da1
    name: ""
    port: 8500
    retrytimeout: 10
    serverslotsbase: 10
    serverslotsgrowthincrement: 10
    serverslotsgrowthtype: linear
    serviceblacklist: []
    servicewhitelist: []
    serviceallowlist: []
    servicedenylist: []
    token: ""
```
