### ISSUE TITLE
Unable to change consul serverslotsbase in dataplane api config

### ISSUE THREAD

**Issue by rhermods** [haproxytech/dataplaneapi#319]
Hi,
After changing serverslotsbase in the dataplane api config file to something like this:
```
service_discovery:
  consuls:
    - address: 127.0.0.1
      enabled: true
      port: 8500
      retrytimeout: 1
      serverslotsbase: 1
      serverslotsgrowthincrement: 3
      serverslotsgrowthtype: exponential
```
and restarting haproxy, the serverslotsbase setting is set to the default value again (10).

Haproxy version: 2.8.3
Dataplane version: v2.9.0

Any ideas or workarounds for this? 
Thanks in advance!
