### ISSUE TITLE
Missing support for `option forwarded` (RFC 7239) in Dataplane API (v3.1.0)

### ISSUE THREAD

**Issue by m-a-rahal-os** [haproxytech/dataplaneapi#376]
Hello !

The `option forwarded` (RFC 7239) doesn't seem to be supported in HAProxy Dataplane API v3.1.0 — unlike `option forwardfor`, which is properly handled.

I searched everywhere for it:
1. Not mentioned in API specification (v3)
2. Not found in source code: when searching for "forwarded", all 10 results are not related this feature.
3. When manually adding "option forwarded" to my backend config, the `GET backend` call doesn't detect it at all, here's an example:
HAProxy version 3.2.0-1
HAProxy Data Plane API v3.1.5 6934995a
```yaml
backend backend_name1 from unnamed_defaults_1
  mode http
  option forwarded
```

With this, the endpoint (GET /v3/services/haproxy/configuration/backends/backend_name1) returns:
```yaml
{
  "from": "unnamed_defaults_1",
  "mode": "http",
  "name": "backend_name1"
}
```

But `option forwardfor` is parsed correctly:

GET /v3/services/haproxy/configuration/backends/backend_name1 returns:
```yaml
{
  "forwardfor": {
    "enabled": "enabled"
  },
  "from": "unnamed_defaults_1",
  "mode": "http",
  "name": "backend_name1"
}
```

---

### Related issues
- #338: closed, but the responder seems to have mistaken the "forwarded" option for "forwardfor"

Thanks for your time !
